### ISSUE TITLE
Domain has expired

### ISSUE THREAD

**Issue by joecdeeson** [adnantopal/extractcss#10]
The web domain has expired for this - is it possible to host it on Github pages or something? This is a great tool!

Thanks,

Joe

**Comment by rtack** [comment]
working again. can be closed

**Comment by dletsche** [comment]
Expired again. I love this tool! Hoping you can bring it back!

**Comment by drugoi** [comment]
Maybe this tool don't need a domain? A simple Github Pages or Surge.sh host will be good and simple.
