### ISSUE TITLE
Extracted CSS - no way to copy/save

### ISSUE THREAD

**Issue by tygertechforce** [adnantopal/extractcss#18]
I am on your website now and pasted my HTML into the left "Type or Paste Your HTML" pane.

I selected my Preferences from the top "Extract" and "Indent CSS With" links and clicked the green "Extract!" button.

The right "Extracted CSS" pane populated correctly with the code.

However, I cannot find a way to SELECT ALL > COPY the code for use in my CSS file.   There seems to be no controls or buttons or links  to do so.

Please advise, as I find this tool EXTREMELY useful and would like to use it.

**Comment by dletsche** [comment]
@TygerTech - I’ve noticed this, too. I should have submitted an issue. Thank you for doing so.

I did find a workaround. You can click in the “Extracted CSS” pane, hit command + a (mac) or control + a (windows), and then hit command + c (mac) or control + c (windows) to copy it to your clipboard. It will look like only a portion was selected, but in reality, everything will be in your clipboard.

**Comment by tygertechforce** [comment]
> @TygerTech - I’ve noticed this, too. I should have submitted an issue. Thank you for doing so.
> 
> I did find a workaround. You can click in the “Extracted CSS” pane, hit command + a (mac) or control + a (windows), and then hit command + c (mac) or control + c (windows) to copy it to your clipboard. It will look like only a portion was selected, but in reality, everything will be in your clipboard.

**Comment by tygertechforce** [comment]
THANK YOU!!!  I appreciate it!
